### ISSUE TITLE
Wat doet deze?

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#10]
Hij staat in de CSS, en hij staat in de HTML, maar ik kan hem niet zien. Waar is deze a[role=button] voor?
https://github.com/Wasknijper/CSS-to-the-Rescue/blob/master/week2/style.css#L194
En wat doet de `witdh: min-content` die daar op staat precies? Wat gebeurt er als je die er af haalt?
https://github.com/Wasknijper/CSS-to-the-Rescue/blob/master/week2/style.css#L203

**Comment by Wasknijper** [comment]
De `a[role=button]` gebruik ik om alle a elementen die zich gedragen als een button er ook op te doen laten lijken. Als er een link staat in een tekst wil ik die niet aanpassen, alleen links die de button role hebben.

De min-content zorgt er voor dat de button width zich aanpast aan de groote van de tekst die er instaat. Als je min-content weghaald neemt hij de hele breedte in, dit komt dan weer omdat hij een `display: block` heeft.
