### ISSUE TITLE
Ampersand op body, niet op H1

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#2]
Met jouw code wordt nu elke ampersand in de hele site vervangen door een sierlijke. Misschien is dat de bedoeling, maar in dit geval denk ik dat je het alleen in de header wil.

**Comment by vasilisvg** [comment]
Bovendien krijgen alleen mensen die de Adobe Garamond Pro hebben geïnstalleerd die ampersand te zien. Daar kunnen meer fallbacks bij.

**Comment by Wasknijper** [comment]
Aangepast.
