### ISSUE TITLE
Font size in px en rem

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#3]
Waarom gebruik je eigenlijk `rem` voor font-size? Er zitten een paar nadelen aan, zoals je hier kan lezen: https://vasilis.nl/nerd/dislike-rem-unit/
Voor andere onderdelen is de `rem` weer uitermate geschikt: https://vasilis.nl/nerd/use-em-rem-right-use-cases/

**Comment by Wasknijper** [comment]
Op bepaalde plekken leek het mij handiger, in bijv. de layout als ik de font-size van de footer kleiner maak. Op andere plaatsen was het beter om het toch aan te passen, zoals de `h1 span` en de `h2` van elkaar los getrokken en aparte regels van gemaakt. Heb alle rem omgezet naar em.
