### ISSUE TITLE
Kleine links

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#4]
Moet elke link in elke paragraaf echt zo klein zijn? In dat geval is dit goede code:
https://github.com/Wasknijper/CSS-to-the-Rescue/blob/master/style.css#L37

Maar ik denk dat dat niet is wat je wil: dit is een uitzonderlijk linkje waar je niet zulke algemene css voor kunt gebruiken.

**Comment by Wasknijper** [comment]
Heb de regel aangepast zodat hij alleen staat op links in de eerste `article` van de `main`
