### ISSUE TITLE
Waarom geen flexbox?

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#5]
Kan je uitleggen waarom `inline-block` in dit geval beter is? Of is flexbox misschien toch nuttiger hier?
https://github.com/Wasknijper/CSS-to-the-Rescue/blob/master/style.css#L207

**Comment by Wasknijper** [comment]
`Inline-block` weggehaald, de ul was al een flexbox, maar was de inline-block vergeten weg te halen.
