### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by vasilisvg** [Wasknijper/CSS-to-the-Rescue#7]
Usability is nog niet optimaal. Het gaat op flink wat punten mis. Kijk eventueel eens of een collega (van UX of vormgeving misschien) je op weg kan helpen?

**Comment by Wasknijper** [comment]
Wat voor een punten gaat het dan mis? De mensen aan wie ik het had laten zien hadden er weinig commentaar op.

**Comment by vasilisvg** [comment]
Hier wat punten die me opvallen:
- http://ndoe.nl/screen/screenshot-1454932945.png
- http://ndoe.nl/screen/screenshot-1454932983.png
- http://ndoe.nl/screen/screenshot-1454932999.png
- http://ndoe.nl/screen/screenshot-1454933057.png

**Comment by Wasknijper** [comment]
Meer flexibiliteit in layout toegevoegt dmv. flex-box wrapping.
